project_name: cloudshell
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    # Keep these synced with Makefile.
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -buildid=
archives:
  - format: binary
nfpms:
  - package_name: cloudshell
    vendor: Ilya Mateyko
    homepage: https://github.com/astrophena/cloudshell
    maintainer: Ilya Mateyko <me@astrophena.name>
    description: Connect to Google Cloud Shell from the terminal.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: bash_autocomplete
        dst: /usr/share/bash-completion/completions/cloudshell
      - src: zsh_autocomplete
        dst: /usr/share/zsh/vendor-completions/_cloudshell
    bindir: /usr/bin
checksum:
  name_template: 'checksums.txt'
snapshot:
  # Keep this synced with Makefile.
  name_template: "{{ .Tag }}-next"
