#!/usr/bin/env bash
#
# Copyright (c) 2019 Ilya Mateyko
#
# The MIT License (MIT)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Build release binary.

[[ ! -z "$DEBUG" ]] && set -x

set -eo pipefail
IFS=$'\n\t'

cd "$(dirname $0)/.."

main() {
  if ! type -p go &>/dev/null; then
    printf "Go is not installed. Install it and try again.\n"
    exit 1
  fi

  export GOOS="${GOOS:=$(go env GOOS)}"
  export GOARCH="${GOARCH:=$(go env GOARCH)}"

  [[ ! -d ./bin ]] && mkdir ./bin

  local o="./bin/cloudshell"
  [[ "$GOOS" == "windows" ]] && o+=".exe"

  go build \
    -o $o \
    -ldflags="-X main.Version="$(date -u +%Y.%m.%d)" -s -w" \
    -mod vendor
}

main "$@"
