name: 'Release'
on:
  push:
    tags: ['v*']
jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
        with:
          fetch-depth: 0
      - name: 'Setup Go'
        uses: 'actions/setup-go@v5.5.0'
      - name: 'Release'
        uses: 'goreleaser/goreleaser-action@v6.4.0'
        with:
          version: 'latest'
          args: 'release --clean'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
