# © 2020 Ilya Mateyko. All rights reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE.md file.

name: Tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Build
        id: build
        run: make
